server:
  port: 8086

spring:
  application:
    name: audit-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  data:
    mongodb:
      uri: mongodb://localhost:27017/auditdb
