server:
  port: 8081

spring:
  application:
    name: auth-service
  config.import: configserver:http://config-server:8888
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/authdb
  #   username: postgres
  #   password: postgres
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true

eureka:
  client:
    service-url:
      defaultZone: service-registry:8761/eureka
