server:
  port: 80

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/authdb
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka.prod.internal/eureka
