server:
  port: 8888

spring:
  application:
    name: config-server
  config.import: configserver:http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: service-registry:8761/eureka
