server:
  port: 8888

spring:
  application:
    name: config-server
  config.import: configserver:http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
    register-with-eureka: true
    fetch-registry: true