server:
  port: 8084

spring:
  application:
    name: match-engine-service
  config.import: configserver:http://config-server:8888
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: match-engine-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.mock.exchange.match_engine_service.model

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
    register-with-eureka: true
    fetch-registry: true