server:
  port: 8082

spring:
  application:
    name: user-service
  config.import: configserver:http://config-server:8888
  # datasource:
  #   url: jdbc:h2:mem:userdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:

  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true

eureka:
  client:
    service-url:
      defaultZone: service-registry:8761/eureka


feign:
  client:
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 3000
        readTimeout: 5000
        requestInterceptors:
          - com.mock.exchange.user_service.config.FeignAuthInterceptor